# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .bucket_detail import BucketDetailParams


class BucketResponseParams(typing_extensions.TypedDict):
    bucket: BucketDetailParams
