# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .bucket_update_detail import BucketUpdateDetailParams


class BucketUpdateResponseParams(typing_extensions.TypedDict):
    bucket: BucketUpdateDetailParams
