# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
import typing
from .bucket_detail import BucketDetailParams
import datetime as dt
from ..core.serialization import FieldMetadata


class GroupDetailParams(typing_extensions.TypedDict):
    buckets: typing_extensions.NotRequired[typing.Sequence[BucketDetailParams]]
    """
    The content buckets associated with the group
    """

    created: typing_extensions.NotRequired[dt.datetime]
    """
    The data time when the group was created, in RFC3339 format
    """

    file_count: typing_extensions.NotRequired[typing_extensions.Annotated[int, FieldMetadata(alias="fileCount")]]
    """
    The number of files contained in the content buckets associated with the group
    """

    file_size: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="fileSize")]]
    """
    The total file size of files contained in the content buckets associated with the group
    """

    group_id: typing_extensions.Annotated[int, FieldMetadata(alias="groupId")]
    name: typing_extensions.NotRequired[str]
    updated: typing_extensions.NotRequired[dt.datetime]
    """
    The data time when the group was last updated, in RFC3339 format
    """
