# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .group_detail import GroupDetailParams


class GroupResponseParams(typing_extensions.TypedDict):
    group: GroupDetailParams
