# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .ingest_response_ingest import IngestResponseIngestParams


class IngestResponseParams(typing_extensions.TypedDict):
    ingest: IngestResponseIngestParams
