# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
from ..core.serialization import FieldMetadata
from ..types.processing_status import ProcessingStatus


class IngestResponseIngestParams(typing_extensions.TypedDict):
    process_id: typing_extensions.Annotated[str, FieldMetadata(alias="processId")]
    status: ProcessingStatus
