# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .search_response_search import SearchResponseSearchParams


class SearchResponseParams(typing_extensions.TypedDict):
    search: SearchResponseSearchParams
