# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
from .meter_detail import MeterDetailParams
from ..core.serialization import FieldMetadata


class SubscriptionDetailMetersParams(typing_extensions.TypedDict):
    file_tokens: typing_extensions.NotRequired[
        typing_extensions.Annotated[MeterDetailParams, FieldMetadata(alias="fileTokens")]
    ]
    searches: typing_extensions.NotRequired[MeterDetailParams]
