# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.message_response import MessageResponse
from ..types.workflow_response import WorkflowResponse
from ..types.workflow_steps import WorkflowSteps
from ..types.workflows_response import WorkflowsResponse
from .raw_client import AsyncRawWorkflowsClient, RawWorkflowsClient
from .types.workflow_get_request_id import WorkflowGetRequestId

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class WorkflowsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWorkflowsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWorkflowsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWorkflowsClient
        """
        return self._raw_client

    def workflow_list(self, *, request_options: typing.Optional[RequestOptions] = None) -> WorkflowsResponse:
        """
        Get all workflows associated with the API key.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowsResponse
            Look up success

        Examples
        --------
        from groundx import GroundX

        client = GroundX(
            api_key="YOUR_API_KEY",
        )
        client.workflows.workflow_list()
        """
        _response = self._raw_client.workflow_list(request_options=request_options)
        return _response.data

    def workflow_create(
        self,
        *,
        name: typing.Optional[str] = OMIT,
        steps: typing.Optional[WorkflowSteps] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WorkflowResponse:
        """
        Create a workflow.

        Parameters
        ----------
        name : typing.Optional[str]
            The name of the workflow being created.

        steps : typing.Optional[WorkflowSteps]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowResponse
            Workflow successfully created

        Examples
        --------
        from groundx import GroundX

        client = GroundX(
            api_key="YOUR_API_KEY",
        )
        client.workflows.workflow_create()
        """
        _response = self._raw_client.workflow_create(name=name, steps=steps, request_options=request_options)
        return _response.data

    def add_to_account(
        self, *, workflow_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> MessageResponse:
        """
        Assigns the given workflow to the customer account and is applied by default to all files unless overridden by document or bucket workflows.

        Parameters
        ----------
        workflow_id : str
            The id of the workflow that is being applied.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            Apply success

        Examples
        --------
        from groundx import GroundX

        client = GroundX(
            api_key="YOUR_API_KEY",
        )
        client.workflows.add_to_account(
            workflow_id="workflowId",
        )
        """
        _response = self._raw_client.add_to_account(workflow_id=workflow_id, request_options=request_options)
        return _response.data

    def remove_from_account(self, *, request_options: typing.Optional[RequestOptions] = None) -> MessageResponse:
        """
        Removes the assigned workflow from the customer account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            Apply success

        Examples
        --------
        from groundx import GroundX

        client = GroundX(
            api_key="YOUR_API_KEY",
        )
        client.workflows.remove_from_account()
        """
        _response = self._raw_client.remove_from_account(request_options=request_options)
        return _response.data

    def add_to_id(
        self, id: int, *, workflow_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> MessageResponse:
        """
        Assigns the given workflow to the group or bucket and is applied by default to all files unless overridden by document workflows.

        Parameters
        ----------
        id : int
            The id of the group or bucket that the workflow will be assigned to.

        workflow_id : str
            The id of the workflow that is being applied.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            Apply success

        Examples
        --------
        from groundx import GroundX

        client = GroundX(
            api_key="YOUR_API_KEY",
        )
        client.workflows.add_to_id(
            id=1,
            workflow_id="workflowId",
        )
        """
        _response = self._raw_client.add_to_id(id, workflow_id=workflow_id, request_options=request_options)
        return _response.data

    def remove_from_id(self, id: int, *, request_options: typing.Optional[RequestOptions] = None) -> MessageResponse:
        """
        Removes the assigned workflow from the customer account.

        Parameters
        ----------
        id : int
            The id of the group or bucket that the workflow will removed from.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            Apply success

        Examples
        --------
        from groundx import GroundX

        client = GroundX(
            api_key="YOUR_API_KEY",
        )
        client.workflows.remove_from_id(
            id=1,
        )
        """
        _response = self._raw_client.remove_from_id(id, request_options=request_options)
        return _response.data

    def workflow_get(
        self, id: WorkflowGetRequestId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> WorkflowResponse:
        """
        look up a specific workflow by groupId, bucketId, or workflowId.

        Parameters
        ----------
        id : WorkflowGetRequestId
            The id of the group, bucket, or workflow to look up.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowResponse
            Look up success

        Examples
        --------
        from groundx import GroundX

        client = GroundX(
            api_key="YOUR_API_KEY",
        )
        client.workflows.workflow_get(
            id=1,
        )
        """
        _response = self._raw_client.workflow_get(id, request_options=request_options)
        return _response.data

    def workflow_update(
        self,
        id: str,
        *,
        workflow_id: str,
        name: typing.Optional[str] = OMIT,
        steps: typing.Optional[WorkflowSteps] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WorkflowResponse:
        """
        Update an existing workflow.

        Parameters
        ----------
        id : str
            The workflowId of the workflow being updated.

        workflow_id : str
            The id of the workflow that is being updated.

        name : typing.Optional[str]
            The name of the workflow being created.

        steps : typing.Optional[WorkflowSteps]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowResponse
            Update success

        Examples
        --------
        from groundx import GroundX

        client = GroundX(
            api_key="YOUR_API_KEY",
        )
        client.workflows.workflow_update(
            id="id",
            workflow_id="workflowId",
        )
        """
        _response = self._raw_client.workflow_update(
            id, workflow_id=workflow_id, name=name, steps=steps, request_options=request_options
        )
        return _response.data

    def workflow_delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> MessageResponse:
        """
        Delete a workflow.

        Parameters
        ----------
        id : str
            The workflowId of the workflow being deleted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            Delete success

        Examples
        --------
        from groundx import GroundX

        client = GroundX(
            api_key="YOUR_API_KEY",
        )
        client.workflows.workflow_delete(
            id="id",
        )
        """
        _response = self._raw_client.workflow_delete(id, request_options=request_options)
        return _response.data


class AsyncWorkflowsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWorkflowsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWorkflowsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWorkflowsClient
        """
        return self._raw_client

    async def workflow_list(self, *, request_options: typing.Optional[RequestOptions] = None) -> WorkflowsResponse:
        """
        Get all workflows associated with the API key.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowsResponse
            Look up success

        Examples
        --------
        import asyncio

        from groundx import AsyncGroundX

        client = AsyncGroundX(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.workflows.workflow_list()


        asyncio.run(main())
        """
        _response = await self._raw_client.workflow_list(request_options=request_options)
        return _response.data

    async def workflow_create(
        self,
        *,
        name: typing.Optional[str] = OMIT,
        steps: typing.Optional[WorkflowSteps] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WorkflowResponse:
        """
        Create a workflow.

        Parameters
        ----------
        name : typing.Optional[str]
            The name of the workflow being created.

        steps : typing.Optional[WorkflowSteps]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowResponse
            Workflow successfully created

        Examples
        --------
        import asyncio

        from groundx import AsyncGroundX

        client = AsyncGroundX(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.workflows.workflow_create()


        asyncio.run(main())
        """
        _response = await self._raw_client.workflow_create(name=name, steps=steps, request_options=request_options)
        return _response.data

    async def add_to_account(
        self, *, workflow_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> MessageResponse:
        """
        Assigns the given workflow to the customer account and is applied by default to all files unless overridden by document or bucket workflows.

        Parameters
        ----------
        workflow_id : str
            The id of the workflow that is being applied.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            Apply success

        Examples
        --------
        import asyncio

        from groundx import AsyncGroundX

        client = AsyncGroundX(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.workflows.add_to_account(
                workflow_id="workflowId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add_to_account(workflow_id=workflow_id, request_options=request_options)
        return _response.data

    async def remove_from_account(self, *, request_options: typing.Optional[RequestOptions] = None) -> MessageResponse:
        """
        Removes the assigned workflow from the customer account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            Apply success

        Examples
        --------
        import asyncio

        from groundx import AsyncGroundX

        client = AsyncGroundX(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.workflows.remove_from_account()


        asyncio.run(main())
        """
        _response = await self._raw_client.remove_from_account(request_options=request_options)
        return _response.data

    async def add_to_id(
        self, id: int, *, workflow_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> MessageResponse:
        """
        Assigns the given workflow to the group or bucket and is applied by default to all files unless overridden by document workflows.

        Parameters
        ----------
        id : int
            The id of the group or bucket that the workflow will be assigned to.

        workflow_id : str
            The id of the workflow that is being applied.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            Apply success

        Examples
        --------
        import asyncio

        from groundx import AsyncGroundX

        client = AsyncGroundX(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.workflows.add_to_id(
                id=1,
                workflow_id="workflowId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add_to_id(id, workflow_id=workflow_id, request_options=request_options)
        return _response.data

    async def remove_from_id(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MessageResponse:
        """
        Removes the assigned workflow from the customer account.

        Parameters
        ----------
        id : int
            The id of the group or bucket that the workflow will removed from.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            Apply success

        Examples
        --------
        import asyncio

        from groundx import AsyncGroundX

        client = AsyncGroundX(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.workflows.remove_from_id(
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove_from_id(id, request_options=request_options)
        return _response.data

    async def workflow_get(
        self, id: WorkflowGetRequestId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> WorkflowResponse:
        """
        look up a specific workflow by groupId, bucketId, or workflowId.

        Parameters
        ----------
        id : WorkflowGetRequestId
            The id of the group, bucket, or workflow to look up.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowResponse
            Look up success

        Examples
        --------
        import asyncio

        from groundx import AsyncGroundX

        client = AsyncGroundX(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.workflows.workflow_get(
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.workflow_get(id, request_options=request_options)
        return _response.data

    async def workflow_update(
        self,
        id: str,
        *,
        workflow_id: str,
        name: typing.Optional[str] = OMIT,
        steps: typing.Optional[WorkflowSteps] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WorkflowResponse:
        """
        Update an existing workflow.

        Parameters
        ----------
        id : str
            The workflowId of the workflow being updated.

        workflow_id : str
            The id of the workflow that is being updated.

        name : typing.Optional[str]
            The name of the workflow being created.

        steps : typing.Optional[WorkflowSteps]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowResponse
            Update success

        Examples
        --------
        import asyncio

        from groundx import AsyncGroundX

        client = AsyncGroundX(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.workflows.workflow_update(
                id="id",
                workflow_id="workflowId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.workflow_update(
            id, workflow_id=workflow_id, name=name, steps=steps, request_options=request_options
        )
        return _response.data

    async def workflow_delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MessageResponse:
        """
        Delete a workflow.

        Parameters
        ----------
        id : str
            The workflowId of the workflow being deleted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            Delete success

        Examples
        --------
        import asyncio

        from groundx import AsyncGroundX

        client = AsyncGroundX(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.workflows.workflow_delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.workflow_delete(id, request_options=request_options)
        return _response.data
