# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.custom_workflow_leaf_field import CustomWorkflowLeafField
from ..types.custom_workflow_output_route import CustomWorkflowOutputRoute
from ..types.custom_workflow_step import CustomWorkflowStep
from ..types.message_response import MessageResponse
from ..types.workflow_request_chunk_strategy import WorkflowRequestChunkStrategy
from ..types.workflow_request_section_strategy import WorkflowRequestSectionStrategy
from ..types.workflow_response import WorkflowResponse
from ..types.workflow_steps import WorkflowSteps
from ..types.workflow_template import WorkflowTemplate
from ..types.workflows_response import WorkflowsResponse
from .types.workflows_get_request_format import WorkflowsGetRequestFormat
from .types.workflows_get_request_id import WorkflowsGetRequestId
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawWorkflowsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[WorkflowsResponse]:
        """
        Get all workflows associated with the API key.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WorkflowsResponse]
            Look up success
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/workflow",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowsResponse,
                    parse_obj_as(
                        type_=WorkflowsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        chunk_strategy: typing.Optional[WorkflowRequestChunkStrategy] = OMIT,
        name: typing.Optional[str] = OMIT,
        yaml: typing.Optional[str] = OMIT,
        extract: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        template: typing.Optional[WorkflowTemplate] = OMIT,
        section_strategy: typing.Optional[WorkflowRequestSectionStrategy] = OMIT,
        steps: typing.Optional[WorkflowSteps] = OMIT,
        custom_steps: typing.Optional[typing.Sequence[CustomWorkflowStep]] = OMIT,
        output_routes: typing.Optional[typing.Sequence[CustomWorkflowOutputRoute]] = OMIT,
        leaf_fields: typing.Optional[typing.Sequence[CustomWorkflowLeafField]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[WorkflowResponse]:
        """
        Create a workflow.

        Parameters
        ----------
        chunk_strategy : typing.Optional[WorkflowRequestChunkStrategy]

        name : typing.Optional[str]
            The name of the workflow being created.

        yaml : typing.Optional[str]
            Authored workflow YAML source. When set, the server compiles it into the canonical workflow structures (steps, prompts, routes) — the other definition fields (extract, customSteps, outputRoutes, leafFields, steps) are derived from it and must be omitted. An extraction-definition-only YAML (groups + field prompts, no workflow block) has its workflow definitions scaffolded server-side.

        extract : typing.Optional[typing.Dict[str, typing.Any]]
            Extract agent definitions.

        template : typing.Optional[WorkflowTemplate]

        section_strategy : typing.Optional[WorkflowRequestSectionStrategy]

        steps : typing.Optional[WorkflowSteps]

        custom_steps : typing.Optional[typing.Sequence[CustomWorkflowStep]]
            Workflow-level custom extraction steps. Legacy fixed steps remain under steps.

        output_routes : typing.Optional[typing.Sequence[CustomWorkflowOutputRoute]]
            Custom output routes. Each record must have exactly one matching leafFields record on finalPath, workflowGroup, workflowField, stepName, level, and outputKey.

        leaf_fields : typing.Optional[typing.Sequence[CustomWorkflowLeafField]]
            Custom leaf-field metadata used to validate route integrity and executable-step field counts.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WorkflowResponse]
            Workflow successfully created
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/workflow",
            method="POST",
            json={
                "chunkStrategy": chunk_strategy,
                "name": name,
                "yaml": yaml,
                "extract": extract,
                "template": template,
                "sectionStrategy": section_strategy,
                "steps": convert_and_respect_annotation_metadata(
                    object_=steps, annotation=WorkflowSteps, direction="write"
                ),
                "customSteps": convert_and_respect_annotation_metadata(
                    object_=custom_steps, annotation=typing.Sequence[CustomWorkflowStep], direction="write"
                ),
                "outputRoutes": convert_and_respect_annotation_metadata(
                    object_=output_routes, annotation=typing.Sequence[CustomWorkflowOutputRoute], direction="write"
                ),
                "leafFields": convert_and_respect_annotation_metadata(
                    object_=leaf_fields, annotation=typing.Sequence[CustomWorkflowLeafField], direction="write"
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowResponse,
                    parse_obj_as(
                        type_=WorkflowResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def validate(
        self,
        *,
        chunk_strategy: typing.Optional[WorkflowRequestChunkStrategy] = OMIT,
        name: typing.Optional[str] = OMIT,
        yaml: typing.Optional[str] = OMIT,
        extract: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        template: typing.Optional[WorkflowTemplate] = OMIT,
        section_strategy: typing.Optional[WorkflowRequestSectionStrategy] = OMIT,
        steps: typing.Optional[WorkflowSteps] = OMIT,
        custom_steps: typing.Optional[typing.Sequence[CustomWorkflowStep]] = OMIT,
        output_routes: typing.Optional[typing.Sequence[CustomWorkflowOutputRoute]] = OMIT,
        leaf_fields: typing.Optional[typing.Sequence[CustomWorkflowLeafField]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[WorkflowResponse]:
        """
        Validate a workflow definition without creating or modifying anything — a distinct operation from create/update. Accepts the same request body as workflow create, including the `yaml` field (authored workflow YAML source, compiled server-side). Returns the compiled workflow; validation failures return the same structured errors as create.

        Parameters
        ----------
        chunk_strategy : typing.Optional[WorkflowRequestChunkStrategy]

        name : typing.Optional[str]
            The name of the workflow being created.

        yaml : typing.Optional[str]
            Authored workflow YAML source. When set, the server compiles it into the canonical workflow structures (steps, prompts, routes) — the other definition fields (extract, customSteps, outputRoutes, leafFields, steps) are derived from it and must be omitted. An extraction-definition-only YAML (groups + field prompts, no workflow block) has its workflow definitions scaffolded server-side.

        extract : typing.Optional[typing.Dict[str, typing.Any]]
            Extract agent definitions.

        template : typing.Optional[WorkflowTemplate]

        section_strategy : typing.Optional[WorkflowRequestSectionStrategy]

        steps : typing.Optional[WorkflowSteps]

        custom_steps : typing.Optional[typing.Sequence[CustomWorkflowStep]]
            Workflow-level custom extraction steps. Legacy fixed steps remain under steps.

        output_routes : typing.Optional[typing.Sequence[CustomWorkflowOutputRoute]]
            Custom output routes. Each record must have exactly one matching leafFields record on finalPath, workflowGroup, workflowField, stepName, level, and outputKey.

        leaf_fields : typing.Optional[typing.Sequence[CustomWorkflowLeafField]]
            Custom leaf-field metadata used to validate route integrity and executable-step field counts.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WorkflowResponse]
            Validation success
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/workflow/validate",
            method="POST",
            json={
                "chunkStrategy": chunk_strategy,
                "name": name,
                "yaml": yaml,
                "extract": extract,
                "template": template,
                "sectionStrategy": section_strategy,
                "steps": convert_and_respect_annotation_metadata(
                    object_=steps, annotation=WorkflowSteps, direction="write"
                ),
                "customSteps": convert_and_respect_annotation_metadata(
                    object_=custom_steps, annotation=typing.Sequence[CustomWorkflowStep], direction="write"
                ),
                "outputRoutes": convert_and_respect_annotation_metadata(
                    object_=output_routes, annotation=typing.Sequence[CustomWorkflowOutputRoute], direction="write"
                ),
                "leafFields": convert_and_respect_annotation_metadata(
                    object_=leaf_fields, annotation=typing.Sequence[CustomWorkflowLeafField], direction="write"
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowResponse,
                    parse_obj_as(
                        type_=WorkflowResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_account(self, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[WorkflowResponse]:
        """
        Get the workflow associated with customer account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WorkflowResponse]
            Look up success
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/workflow/relationship",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowResponse,
                    parse_obj_as(
                        type_=WorkflowResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def add_to_account(
        self, *, workflow_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[MessageResponse]:
        """
        Assigns the given workflow to the customer account and is applied by default to all files unless overridden by document or bucket workflows.

        Parameters
        ----------
        workflow_id : str
            The id of the workflow that is being applied.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MessageResponse]
            Apply success
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/workflow/relationship",
            method="POST",
            json={
                "workflowId": workflow_id,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageResponse,
                    parse_obj_as(
                        type_=MessageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def remove_from_account(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[MessageResponse]:
        """
        Removes the assigned workflow from the customer account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MessageResponse]
            Apply success
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/workflow/relationship",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageResponse,
                    parse_obj_as(
                        type_=MessageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def add_to_id(
        self, id: int, *, workflow_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[MessageResponse]:
        """
        Assigns the given workflow to the group or bucket and is applied by default to all files unless overridden by document workflows.

        Parameters
        ----------
        id : int
            The id of the group or bucket that the workflow will be assigned to.

        workflow_id : str
            The id of the workflow that is being applied.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MessageResponse]
            Apply success
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/workflow/relationship/{encode_path_param(id)}",
            method="POST",
            json={
                "workflowId": workflow_id,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageResponse,
                    parse_obj_as(
                        type_=MessageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def remove_from_id(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[MessageResponse]:
        """
        Removes the assigned workflow from the customer account.

        Parameters
        ----------
        id : int
            The id of the group or bucket that the workflow will removed from.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MessageResponse]
            Apply success
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/workflow/relationship/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageResponse,
                    parse_obj_as(
                        type_=MessageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(
        self,
        id: WorkflowsGetRequestId,
        *,
        format: typing.Optional[WorkflowsGetRequestFormat] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[WorkflowResponse]:
        """
        look up a specific workflow by groupId, bucketId, or workflowId.

        Parameters
        ----------
        id : WorkflowsGetRequestId
            The id of the group, bucket, or workflow to look up.

        format : typing.Optional[WorkflowsGetRequestFormat]
            Response format. `yaml` returns the stored authored workflow YAML source verbatim (absent for workflows created via compiled JSON).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WorkflowResponse]
            Look up success
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/workflow/{encode_path_param(id)}",
            method="GET",
            params={
                "format": format,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowResponse,
                    parse_obj_as(
                        type_=WorkflowResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update(
        self,
        id: str,
        *,
        chunk_strategy: typing.Optional[WorkflowRequestChunkStrategy] = OMIT,
        name: typing.Optional[str] = OMIT,
        yaml: typing.Optional[str] = OMIT,
        extract: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        template: typing.Optional[WorkflowTemplate] = OMIT,
        section_strategy: typing.Optional[WorkflowRequestSectionStrategy] = OMIT,
        steps: typing.Optional[WorkflowSteps] = OMIT,
        custom_steps: typing.Optional[typing.Sequence[CustomWorkflowStep]] = OMIT,
        output_routes: typing.Optional[typing.Sequence[CustomWorkflowOutputRoute]] = OMIT,
        leaf_fields: typing.Optional[typing.Sequence[CustomWorkflowLeafField]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[WorkflowResponse]:
        """
        Update an existing workflow. The request body is the desired custom overlay relative to GroundX defaults, not a delta against the currently stored custom workflow. Omitted steps and omitted step config fields return to defaults. Step null disables or clears that default step. For step configs, omitted prompt and prompt: {} use the default prompt group; prompt: null intentionally uses no prompt group. A name-only update is not metadata-only; include custom processing settings again if they should remain in effect.

        Parameters
        ----------
        id : str
            The workflowId of the workflow being updated.

        chunk_strategy : typing.Optional[WorkflowRequestChunkStrategy]

        name : typing.Optional[str]
            The name of the workflow being created.

        yaml : typing.Optional[str]
            Authored workflow YAML source. When set, the server compiles it into the canonical workflow structures (steps, prompts, routes) — the other definition fields (extract, customSteps, outputRoutes, leafFields, steps) are derived from it and must be omitted. An extraction-definition-only YAML (groups + field prompts, no workflow block) has its workflow definitions scaffolded server-side.

        extract : typing.Optional[typing.Dict[str, typing.Any]]
            Extract agent definitions.

        template : typing.Optional[WorkflowTemplate]

        section_strategy : typing.Optional[WorkflowRequestSectionStrategy]

        steps : typing.Optional[WorkflowSteps]

        custom_steps : typing.Optional[typing.Sequence[CustomWorkflowStep]]
            Workflow-level custom extraction steps. Legacy fixed steps remain under steps.

        output_routes : typing.Optional[typing.Sequence[CustomWorkflowOutputRoute]]
            Custom output routes. Each record must have exactly one matching leafFields record on finalPath, workflowGroup, workflowField, stepName, level, and outputKey.

        leaf_fields : typing.Optional[typing.Sequence[CustomWorkflowLeafField]]
            Custom leaf-field metadata used to validate route integrity and executable-step field counts.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WorkflowResponse]
            Update success
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/workflow/{encode_path_param(id)}",
            method="PUT",
            json={
                "chunkStrategy": chunk_strategy,
                "name": name,
                "yaml": yaml,
                "extract": extract,
                "template": template,
                "sectionStrategy": section_strategy,
                "steps": convert_and_respect_annotation_metadata(
                    object_=steps, annotation=WorkflowSteps, direction="write"
                ),
                "customSteps": convert_and_respect_annotation_metadata(
                    object_=custom_steps, annotation=typing.Sequence[CustomWorkflowStep], direction="write"
                ),
                "outputRoutes": convert_and_respect_annotation_metadata(
                    object_=output_routes, annotation=typing.Sequence[CustomWorkflowOutputRoute], direction="write"
                ),
                "leafFields": convert_and_respect_annotation_metadata(
                    object_=leaf_fields, annotation=typing.Sequence[CustomWorkflowLeafField], direction="write"
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowResponse,
                    parse_obj_as(
                        type_=WorkflowResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[MessageResponse]:
        """
        Delete a workflow.

        Parameters
        ----------
        id : str
            The workflowId of the workflow being deleted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MessageResponse]
            Delete success
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/workflow/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageResponse,
                    parse_obj_as(
                        type_=MessageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawWorkflowsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[WorkflowsResponse]:
        """
        Get all workflows associated with the API key.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WorkflowsResponse]
            Look up success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/workflow",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowsResponse,
                    parse_obj_as(
                        type_=WorkflowsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        chunk_strategy: typing.Optional[WorkflowRequestChunkStrategy] = OMIT,
        name: typing.Optional[str] = OMIT,
        yaml: typing.Optional[str] = OMIT,
        extract: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        template: typing.Optional[WorkflowTemplate] = OMIT,
        section_strategy: typing.Optional[WorkflowRequestSectionStrategy] = OMIT,
        steps: typing.Optional[WorkflowSteps] = OMIT,
        custom_steps: typing.Optional[typing.Sequence[CustomWorkflowStep]] = OMIT,
        output_routes: typing.Optional[typing.Sequence[CustomWorkflowOutputRoute]] = OMIT,
        leaf_fields: typing.Optional[typing.Sequence[CustomWorkflowLeafField]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[WorkflowResponse]:
        """
        Create a workflow.

        Parameters
        ----------
        chunk_strategy : typing.Optional[WorkflowRequestChunkStrategy]

        name : typing.Optional[str]
            The name of the workflow being created.

        yaml : typing.Optional[str]
            Authored workflow YAML source. When set, the server compiles it into the canonical workflow structures (steps, prompts, routes) — the other definition fields (extract, customSteps, outputRoutes, leafFields, steps) are derived from it and must be omitted. An extraction-definition-only YAML (groups + field prompts, no workflow block) has its workflow definitions scaffolded server-side.

        extract : typing.Optional[typing.Dict[str, typing.Any]]
            Extract agent definitions.

        template : typing.Optional[WorkflowTemplate]

        section_strategy : typing.Optional[WorkflowRequestSectionStrategy]

        steps : typing.Optional[WorkflowSteps]

        custom_steps : typing.Optional[typing.Sequence[CustomWorkflowStep]]
            Workflow-level custom extraction steps. Legacy fixed steps remain under steps.

        output_routes : typing.Optional[typing.Sequence[CustomWorkflowOutputRoute]]
            Custom output routes. Each record must have exactly one matching leafFields record on finalPath, workflowGroup, workflowField, stepName, level, and outputKey.

        leaf_fields : typing.Optional[typing.Sequence[CustomWorkflowLeafField]]
            Custom leaf-field metadata used to validate route integrity and executable-step field counts.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WorkflowResponse]
            Workflow successfully created
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/workflow",
            method="POST",
            json={
                "chunkStrategy": chunk_strategy,
                "name": name,
                "yaml": yaml,
                "extract": extract,
                "template": template,
                "sectionStrategy": section_strategy,
                "steps": convert_and_respect_annotation_metadata(
                    object_=steps, annotation=WorkflowSteps, direction="write"
                ),
                "customSteps": convert_and_respect_annotation_metadata(
                    object_=custom_steps, annotation=typing.Sequence[CustomWorkflowStep], direction="write"
                ),
                "outputRoutes": convert_and_respect_annotation_metadata(
                    object_=output_routes, annotation=typing.Sequence[CustomWorkflowOutputRoute], direction="write"
                ),
                "leafFields": convert_and_respect_annotation_metadata(
                    object_=leaf_fields, annotation=typing.Sequence[CustomWorkflowLeafField], direction="write"
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowResponse,
                    parse_obj_as(
                        type_=WorkflowResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def validate(
        self,
        *,
        chunk_strategy: typing.Optional[WorkflowRequestChunkStrategy] = OMIT,
        name: typing.Optional[str] = OMIT,
        yaml: typing.Optional[str] = OMIT,
        extract: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        template: typing.Optional[WorkflowTemplate] = OMIT,
        section_strategy: typing.Optional[WorkflowRequestSectionStrategy] = OMIT,
        steps: typing.Optional[WorkflowSteps] = OMIT,
        custom_steps: typing.Optional[typing.Sequence[CustomWorkflowStep]] = OMIT,
        output_routes: typing.Optional[typing.Sequence[CustomWorkflowOutputRoute]] = OMIT,
        leaf_fields: typing.Optional[typing.Sequence[CustomWorkflowLeafField]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[WorkflowResponse]:
        """
        Validate a workflow definition without creating or modifying anything — a distinct operation from create/update. Accepts the same request body as workflow create, including the `yaml` field (authored workflow YAML source, compiled server-side). Returns the compiled workflow; validation failures return the same structured errors as create.

        Parameters
        ----------
        chunk_strategy : typing.Optional[WorkflowRequestChunkStrategy]

        name : typing.Optional[str]
            The name of the workflow being created.

        yaml : typing.Optional[str]
            Authored workflow YAML source. When set, the server compiles it into the canonical workflow structures (steps, prompts, routes) — the other definition fields (extract, customSteps, outputRoutes, leafFields, steps) are derived from it and must be omitted. An extraction-definition-only YAML (groups + field prompts, no workflow block) has its workflow definitions scaffolded server-side.

        extract : typing.Optional[typing.Dict[str, typing.Any]]
            Extract agent definitions.

        template : typing.Optional[WorkflowTemplate]

        section_strategy : typing.Optional[WorkflowRequestSectionStrategy]

        steps : typing.Optional[WorkflowSteps]

        custom_steps : typing.Optional[typing.Sequence[CustomWorkflowStep]]
            Workflow-level custom extraction steps. Legacy fixed steps remain under steps.

        output_routes : typing.Optional[typing.Sequence[CustomWorkflowOutputRoute]]
            Custom output routes. Each record must have exactly one matching leafFields record on finalPath, workflowGroup, workflowField, stepName, level, and outputKey.

        leaf_fields : typing.Optional[typing.Sequence[CustomWorkflowLeafField]]
            Custom leaf-field metadata used to validate route integrity and executable-step field counts.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WorkflowResponse]
            Validation success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/workflow/validate",
            method="POST",
            json={
                "chunkStrategy": chunk_strategy,
                "name": name,
                "yaml": yaml,
                "extract": extract,
                "template": template,
                "sectionStrategy": section_strategy,
                "steps": convert_and_respect_annotation_metadata(
                    object_=steps, annotation=WorkflowSteps, direction="write"
                ),
                "customSteps": convert_and_respect_annotation_metadata(
                    object_=custom_steps, annotation=typing.Sequence[CustomWorkflowStep], direction="write"
                ),
                "outputRoutes": convert_and_respect_annotation_metadata(
                    object_=output_routes, annotation=typing.Sequence[CustomWorkflowOutputRoute], direction="write"
                ),
                "leafFields": convert_and_respect_annotation_metadata(
                    object_=leaf_fields, annotation=typing.Sequence[CustomWorkflowLeafField], direction="write"
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowResponse,
                    parse_obj_as(
                        type_=WorkflowResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_account(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[WorkflowResponse]:
        """
        Get the workflow associated with customer account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WorkflowResponse]
            Look up success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/workflow/relationship",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowResponse,
                    parse_obj_as(
                        type_=WorkflowResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def add_to_account(
        self, *, workflow_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[MessageResponse]:
        """
        Assigns the given workflow to the customer account and is applied by default to all files unless overridden by document or bucket workflows.

        Parameters
        ----------
        workflow_id : str
            The id of the workflow that is being applied.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MessageResponse]
            Apply success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/workflow/relationship",
            method="POST",
            json={
                "workflowId": workflow_id,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageResponse,
                    parse_obj_as(
                        type_=MessageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def remove_from_account(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[MessageResponse]:
        """
        Removes the assigned workflow from the customer account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MessageResponse]
            Apply success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/workflow/relationship",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageResponse,
                    parse_obj_as(
                        type_=MessageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def add_to_id(
        self, id: int, *, workflow_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[MessageResponse]:
        """
        Assigns the given workflow to the group or bucket and is applied by default to all files unless overridden by document workflows.

        Parameters
        ----------
        id : int
            The id of the group or bucket that the workflow will be assigned to.

        workflow_id : str
            The id of the workflow that is being applied.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MessageResponse]
            Apply success
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/workflow/relationship/{encode_path_param(id)}",
            method="POST",
            json={
                "workflowId": workflow_id,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageResponse,
                    parse_obj_as(
                        type_=MessageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def remove_from_id(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[MessageResponse]:
        """
        Removes the assigned workflow from the customer account.

        Parameters
        ----------
        id : int
            The id of the group or bucket that the workflow will removed from.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MessageResponse]
            Apply success
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/workflow/relationship/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageResponse,
                    parse_obj_as(
                        type_=MessageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self,
        id: WorkflowsGetRequestId,
        *,
        format: typing.Optional[WorkflowsGetRequestFormat] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[WorkflowResponse]:
        """
        look up a specific workflow by groupId, bucketId, or workflowId.

        Parameters
        ----------
        id : WorkflowsGetRequestId
            The id of the group, bucket, or workflow to look up.

        format : typing.Optional[WorkflowsGetRequestFormat]
            Response format. `yaml` returns the stored authored workflow YAML source verbatim (absent for workflows created via compiled JSON).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WorkflowResponse]
            Look up success
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/workflow/{encode_path_param(id)}",
            method="GET",
            params={
                "format": format,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowResponse,
                    parse_obj_as(
                        type_=WorkflowResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update(
        self,
        id: str,
        *,
        chunk_strategy: typing.Optional[WorkflowRequestChunkStrategy] = OMIT,
        name: typing.Optional[str] = OMIT,
        yaml: typing.Optional[str] = OMIT,
        extract: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        template: typing.Optional[WorkflowTemplate] = OMIT,
        section_strategy: typing.Optional[WorkflowRequestSectionStrategy] = OMIT,
        steps: typing.Optional[WorkflowSteps] = OMIT,
        custom_steps: typing.Optional[typing.Sequence[CustomWorkflowStep]] = OMIT,
        output_routes: typing.Optional[typing.Sequence[CustomWorkflowOutputRoute]] = OMIT,
        leaf_fields: typing.Optional[typing.Sequence[CustomWorkflowLeafField]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[WorkflowResponse]:
        """
        Update an existing workflow. The request body is the desired custom overlay relative to GroundX defaults, not a delta against the currently stored custom workflow. Omitted steps and omitted step config fields return to defaults. Step null disables or clears that default step. For step configs, omitted prompt and prompt: {} use the default prompt group; prompt: null intentionally uses no prompt group. A name-only update is not metadata-only; include custom processing settings again if they should remain in effect.

        Parameters
        ----------
        id : str
            The workflowId of the workflow being updated.

        chunk_strategy : typing.Optional[WorkflowRequestChunkStrategy]

        name : typing.Optional[str]
            The name of the workflow being created.

        yaml : typing.Optional[str]
            Authored workflow YAML source. When set, the server compiles it into the canonical workflow structures (steps, prompts, routes) — the other definition fields (extract, customSteps, outputRoutes, leafFields, steps) are derived from it and must be omitted. An extraction-definition-only YAML (groups + field prompts, no workflow block) has its workflow definitions scaffolded server-side.

        extract : typing.Optional[typing.Dict[str, typing.Any]]
            Extract agent definitions.

        template : typing.Optional[WorkflowTemplate]

        section_strategy : typing.Optional[WorkflowRequestSectionStrategy]

        steps : typing.Optional[WorkflowSteps]

        custom_steps : typing.Optional[typing.Sequence[CustomWorkflowStep]]
            Workflow-level custom extraction steps. Legacy fixed steps remain under steps.

        output_routes : typing.Optional[typing.Sequence[CustomWorkflowOutputRoute]]
            Custom output routes. Each record must have exactly one matching leafFields record on finalPath, workflowGroup, workflowField, stepName, level, and outputKey.

        leaf_fields : typing.Optional[typing.Sequence[CustomWorkflowLeafField]]
            Custom leaf-field metadata used to validate route integrity and executable-step field counts.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WorkflowResponse]
            Update success
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/workflow/{encode_path_param(id)}",
            method="PUT",
            json={
                "chunkStrategy": chunk_strategy,
                "name": name,
                "yaml": yaml,
                "extract": extract,
                "template": template,
                "sectionStrategy": section_strategy,
                "steps": convert_and_respect_annotation_metadata(
                    object_=steps, annotation=WorkflowSteps, direction="write"
                ),
                "customSteps": convert_and_respect_annotation_metadata(
                    object_=custom_steps, annotation=typing.Sequence[CustomWorkflowStep], direction="write"
                ),
                "outputRoutes": convert_and_respect_annotation_metadata(
                    object_=output_routes, annotation=typing.Sequence[CustomWorkflowOutputRoute], direction="write"
                ),
                "leafFields": convert_and_respect_annotation_metadata(
                    object_=leaf_fields, annotation=typing.Sequence[CustomWorkflowLeafField], direction="write"
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowResponse,
                    parse_obj_as(
                        type_=WorkflowResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[MessageResponse]:
        """
        Delete a workflow.

        Parameters
        ----------
        id : str
            The workflowId of the workflow being deleted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MessageResponse]
            Delete success
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/workflow/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageResponse,
                    parse_obj_as(
                        type_=MessageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
