# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.api_key_request_api_key import ApiKeyRequestApiKey
from ..types.api_key_response import ApiKeyResponse
from ..types.message_response import MessageResponse
from .raw_client import AsyncRawApiKeyClient, RawApiKeyClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ApiKeyClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawApiKeyClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawApiKeyClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawApiKeyClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> ApiKeyResponse:
        """
        List all API keys within your GroundX account

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyResponse
            Look up success

        Examples
        --------
        from groundx import GroundX

        client = GroundX(
            api_key="YOUR_API_KEY",
        )
        client.api_key.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def create(
        self, *, api_key: ApiKeyRequestApiKey, request_options: typing.Optional[RequestOptions] = None
    ) -> ApiKeyResponse:
        """
        Create a new API key.

        Parameters
        ----------
        api_key : ApiKeyRequestApiKey

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyResponse
            API key successfully created

        Examples
        --------
        from groundx import ApiKeyRequestApiKey, GroundX

        client = GroundX(
            api_key="YOUR_API_KEY",
        )
        client.api_key.create(
            api_key=ApiKeyRequestApiKey(
                name="your_apikey_name",
            ),
        )
        """
        _response = self._raw_client.create(api_key=api_key, request_options=request_options)
        return _response.data

    def update(
        self, api_key_: str, *, api_key: ApiKeyRequestApiKey, request_options: typing.Optional[RequestOptions] = None
    ) -> ApiKeyResponse:
        """
        Rename an API key.

        Parameters
        ----------
        api_key_ : str
            The API key being updated.

        api_key : ApiKeyRequestApiKey

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyResponse
            API key successfully updated

        Examples
        --------
        from groundx import ApiKeyRequestApiKey, GroundX

        client = GroundX(
            api_key="YOUR_API_KEY",
        )
        client.api_key.update(
            api_key_="apiKey",
            api_key=ApiKeyRequestApiKey(
                name="your_apikey_name",
            ),
        )
        """
        _response = self._raw_client.update(api_key_, api_key=api_key, request_options=request_options)
        return _response.data

    def delete(self, api_key: str, *, request_options: typing.Optional[RequestOptions] = None) -> MessageResponse:
        """
        Delete an API key.

        Parameters
        ----------
        api_key : str
            The API key being deleted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            API key successfully deleted

        Examples
        --------
        from groundx import GroundX

        client = GroundX(
            api_key="YOUR_API_KEY",
        )
        client.api_key.delete(
            api_key="apiKey",
        )
        """
        _response = self._raw_client.delete(api_key, request_options=request_options)
        return _response.data


class AsyncApiKeyClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawApiKeyClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawApiKeyClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawApiKeyClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> ApiKeyResponse:
        """
        List all API keys within your GroundX account

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyResponse
            Look up success

        Examples
        --------
        import asyncio

        from groundx import AsyncGroundX

        client = AsyncGroundX(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.api_key.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def create(
        self, *, api_key: ApiKeyRequestApiKey, request_options: typing.Optional[RequestOptions] = None
    ) -> ApiKeyResponse:
        """
        Create a new API key.

        Parameters
        ----------
        api_key : ApiKeyRequestApiKey

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyResponse
            API key successfully created

        Examples
        --------
        import asyncio

        from groundx import ApiKeyRequestApiKey, AsyncGroundX

        client = AsyncGroundX(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.api_key.create(
                api_key=ApiKeyRequestApiKey(
                    name="your_apikey_name",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(api_key=api_key, request_options=request_options)
        return _response.data

    async def update(
        self, api_key_: str, *, api_key: ApiKeyRequestApiKey, request_options: typing.Optional[RequestOptions] = None
    ) -> ApiKeyResponse:
        """
        Rename an API key.

        Parameters
        ----------
        api_key_ : str
            The API key being updated.

        api_key : ApiKeyRequestApiKey

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyResponse
            API key successfully updated

        Examples
        --------
        import asyncio

        from groundx import ApiKeyRequestApiKey, AsyncGroundX

        client = AsyncGroundX(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.api_key.update(
                api_key_="apiKey",
                api_key=ApiKeyRequestApiKey(
                    name="your_apikey_name",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(api_key_, api_key=api_key, request_options=request_options)
        return _response.data

    async def delete(self, api_key: str, *, request_options: typing.Optional[RequestOptions] = None) -> MessageResponse:
        """
        Delete an API key.

        Parameters
        ----------
        api_key : str
            The API key being deleted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            API key successfully deleted

        Examples
        --------
        import asyncio

        from groundx import AsyncGroundX

        client = AsyncGroundX(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.api_key.delete(
                api_key="apiKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(api_key, request_options=request_options)
        return _response.data
