# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import httpx
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .environment import GroundXEnvironment

if typing.TYPE_CHECKING:
    from .buckets.client import AsyncBucketsClient, BucketsClient
    from .customer.client import AsyncCustomerClient, CustomerClient
    from .documents.client import AsyncDocumentsClient, DocumentsClient
    from .groups.client import AsyncGroupsClient, GroupsClient
    from .health.client import AsyncHealthClient, HealthClient
    from .search.client import AsyncSearchClient, SearchClient
    from .workflows.client import AsyncWorkflowsClient, WorkflowsClient


class GroundXBase:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : GroundXEnvironment
        The environment to use for requests from the client. from .environment import GroundXEnvironment



        Defaults to GroundXEnvironment.DEFAULT



    api_key : str
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    Examples
    --------
    from groundx import GroundX

    client = GroundX(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: GroundXEnvironment = GroundXEnvironment.DEFAULT,
        api_key: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
        )
        self._documents: typing.Optional[DocumentsClient] = None
        self._search: typing.Optional[SearchClient] = None
        self._buckets: typing.Optional[BucketsClient] = None
        self._groups: typing.Optional[GroupsClient] = None
        self._workflows: typing.Optional[WorkflowsClient] = None
        self._customer: typing.Optional[CustomerClient] = None
        self._health: typing.Optional[HealthClient] = None

    @property
    def documents(self):
        if self._documents is None:
            from .documents.client import DocumentsClient  # noqa: E402

            self._documents = DocumentsClient(client_wrapper=self._client_wrapper)
        return self._documents

    @property
    def search(self):
        if self._search is None:
            from .search.client import SearchClient  # noqa: E402

            self._search = SearchClient(client_wrapper=self._client_wrapper)
        return self._search

    @property
    def buckets(self):
        if self._buckets is None:
            from .buckets.client import BucketsClient  # noqa: E402

            self._buckets = BucketsClient(client_wrapper=self._client_wrapper)
        return self._buckets

    @property
    def groups(self):
        if self._groups is None:
            from .groups.client import GroupsClient  # noqa: E402

            self._groups = GroupsClient(client_wrapper=self._client_wrapper)
        return self._groups

    @property
    def workflows(self):
        if self._workflows is None:
            from .workflows.client import WorkflowsClient  # noqa: E402

            self._workflows = WorkflowsClient(client_wrapper=self._client_wrapper)
        return self._workflows

    @property
    def customer(self):
        if self._customer is None:
            from .customer.client import CustomerClient  # noqa: E402

            self._customer = CustomerClient(client_wrapper=self._client_wrapper)
        return self._customer

    @property
    def health(self):
        if self._health is None:
            from .health.client import HealthClient  # noqa: E402

            self._health = HealthClient(client_wrapper=self._client_wrapper)
        return self._health


class AsyncGroundXBase:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : GroundXEnvironment
        The environment to use for requests from the client. from .environment import GroundXEnvironment



        Defaults to GroundXEnvironment.DEFAULT



    api_key : str
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    Examples
    --------
    from groundx import AsyncGroundX

    client = AsyncGroundX(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: GroundXEnvironment = GroundXEnvironment.DEFAULT,
        api_key: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.AsyncClient(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.AsyncClient(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
        )
        self._documents: typing.Optional[AsyncDocumentsClient] = None
        self._search: typing.Optional[AsyncSearchClient] = None
        self._buckets: typing.Optional[AsyncBucketsClient] = None
        self._groups: typing.Optional[AsyncGroupsClient] = None
        self._workflows: typing.Optional[AsyncWorkflowsClient] = None
        self._customer: typing.Optional[AsyncCustomerClient] = None
        self._health: typing.Optional[AsyncHealthClient] = None

    @property
    def documents(self):
        if self._documents is None:
            from .documents.client import AsyncDocumentsClient  # noqa: E402

            self._documents = AsyncDocumentsClient(client_wrapper=self._client_wrapper)
        return self._documents

    @property
    def search(self):
        if self._search is None:
            from .search.client import AsyncSearchClient  # noqa: E402

            self._search = AsyncSearchClient(client_wrapper=self._client_wrapper)
        return self._search

    @property
    def buckets(self):
        if self._buckets is None:
            from .buckets.client import AsyncBucketsClient  # noqa: E402

            self._buckets = AsyncBucketsClient(client_wrapper=self._client_wrapper)
        return self._buckets

    @property
    def groups(self):
        if self._groups is None:
            from .groups.client import AsyncGroupsClient  # noqa: E402

            self._groups = AsyncGroupsClient(client_wrapper=self._client_wrapper)
        return self._groups

    @property
    def workflows(self):
        if self._workflows is None:
            from .workflows.client import AsyncWorkflowsClient  # noqa: E402

            self._workflows = AsyncWorkflowsClient(client_wrapper=self._client_wrapper)
        return self._workflows

    @property
    def customer(self):
        if self._customer is None:
            from .customer.client import AsyncCustomerClient  # noqa: E402

            self._customer = AsyncCustomerClient(client_wrapper=self._client_wrapper)
        return self._customer

    @property
    def health(self):
        if self._health is None:
            from .health.client import AsyncHealthClient  # noqa: E402

            self._health = AsyncHealthClient(client_wrapper=self._client_wrapper)
        return self._health


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: GroundXEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
