# This file was auto-generated by Fern from our API Definition.

from .document_remote_ingest_request_documents_item import DocumentRemoteIngestRequestDocumentsItemParams
from .website_crawl_request_websites_item import WebsiteCrawlRequestWebsitesItemParams

__all__ = ["DocumentRemoteIngestRequestDocumentsItemParams", "WebsiteCrawlRequestWebsitesItemParams"]
