# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
from ...core.serialization import FieldMetadata
from ...types.document_type import DocumentType
import typing


class DocumentRemoteIngestRequestDocumentsItemParams(typing_extensions.TypedDict):
    bucket_id: typing_extensions.Annotated[int, FieldMetadata(alias="bucketId")]
    """
    the bucketId of the bucket which this remote file will be ingested to.
    """

    file_name: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="fileName")]]
    """
    The name of the file being ingested
    """

    file_type: typing_extensions.NotRequired[typing_extensions.Annotated[DocumentType, FieldMetadata(alias="fileType")]]
    search_data: typing_extensions.NotRequired[
        typing_extensions.Annotated[typing.Dict[str, typing.Optional[typing.Any]], FieldMetadata(alias="searchData")]
    ]
    """
    Custom metadata which can be used to influence GroundX's search functionality. This data can be used to further hone GroundX search.
    """

    source_url: typing_extensions.Annotated[str, FieldMetadata(alias="sourceUrl")]
    """
    The URL of the document being ingested by GroundX.
    """
