"""Persisted custom-workflow read tolerance (openspec:
fix-persisted-workflow-derivation, re-scoped after fresh-scan review P1/P2).

SDK scope (this file):
1. The stored (writer-owned) `schema_hash` NEVER gates loading — the 2026-07-08
   prod outage was a reader recomputing a hash with its own canonicalization
   and hard-failing every harness-dialect workflow.
2. `workflow_field_paths` preserves route `final_path` VERBATIM — `*` tokens
   are load-bearing for the SDK's own row routing (field-level lists). The
   2-segment contract belongs solely to the Arcadia reassembly export
   (internal-arcadia-agents), which normalizes at its own boundary; those
   tests live there.
3. Structural corruption still fails via structural validation, not hashes.

Fixture provenance: `harness_dialect_persisted_extract.json` is fully
synthetic (generated via the SDK compiler, mutated to the harness dialect) —
it mirrors the structure of the 2026-07-08 failed prod deploy without any
production prompt or schema content.
"""

import copy
import json
import pathlib
import typing

import pytest

from groundx.extract import prepare_extraction_yaml

FIXTURES = pathlib.Path(__file__).parent / "fixtures"


def _load(name: str) -> typing.Dict[str, typing.Any]:
    with open(FIXTURES / name) as f:
        return typing.cast(typing.Dict[str, typing.Any], json.load(f))


def _persisted_extract() -> typing.Dict[str, typing.Any]:
    # Fully SYNTHETIC harness-dialect persisted extract (invented domain/fields/
    # prompts), generated by the SDK's own compiler then mutated to the harness
    # dialect: starred group-repetition routes, is_repeated flags, embedded
    # agent_chain, and a writer-style schema_hash no reader recompute matches.
    return _load("harness_dialect_persisted_extract.json")


def test_harness_dialect_stored_hash_never_gates_loading() -> None:
    """The prod outage: reader recomputed a hash over re-normalized structures
    and hard-failed on the writer's hash. Loading must succeed with the
    harness-dialect hash intact."""
    persisted = _persisted_extract()
    workflow = persisted["workflow"]
    assert workflow.get("schema_hash"), "fixture must carry the writer hash"
    prepared = prepare_extraction_yaml(persisted)  # must not raise
    assert prepared.workflow_field_paths


def test_field_paths_preserve_final_path_verbatim() -> None:
    """`*` tokens are SDK row-routing vocabulary and must survive derivation
    untouched (normalization is the Arcadia export's job, at its boundary)."""
    persisted = _persisted_extract()
    routes = persisted["workflow"]["output_routes"]
    expected = {
        (r["workflow_group"], r["workflow_field"]): r["final_path"] for r in routes
    }
    starred = [p for p in expected.values() if "/*/" in p]
    assert starred, "fixture must contain harness-dialect starred routes"

    prepared = prepare_extraction_yaml(persisted)
    for (group, field), final_path in expected.items():
        assert prepared.workflow_field_paths[group][field] == final_path


def test_recomputed_hash_is_attached_not_compared() -> None:
    """The loader attaches its own canonical recompute for downstream use; the
    writer's differing hash is never an error."""
    persisted = _persisted_extract()
    stored_hash = persisted["workflow"]["schema_hash"]
    prepared = prepare_extraction_yaml(persisted)
    attached = prepared.persisted_workflow_extract["workflow"]["schema_hash"]
    assert attached  # present for downstream use
    # The live divergence: stored f1a2… (Go writer) vs SDK recompute — both valid.
    assert stored_hash != attached or stored_hash == attached  # never an error either way


def test_structural_corruption_still_fails() -> None:
    """Integrity is structural, not hash-based — a route pointing at an
    undefined step must still raise a descriptive error."""
    persisted = _persisted_extract()
    routes = persisted["workflow"]["output_routes"]
    routes[0]["step_name"] = "no_such_step"
    with pytest.raises(ValueError):
        prepare_extraction_yaml(persisted)
