# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
from ..core.serialization import FieldMetadata


class BoundingBoxDetailParams(typing_extensions.TypedDict):
    bottom_right_x: typing_extensions.NotRequired[
        typing_extensions.Annotated[float, FieldMetadata(alias="bottomRightX")]
    ]
    """
    The x coordinate of the lower right corner of the bounding box
    """

    bottom_right_y: typing_extensions.NotRequired[
        typing_extensions.Annotated[float, FieldMetadata(alias="bottomRightY")]
    ]
    """
    The y coordinate of the lower right corner of the bounding box
    """

    page_number: typing_extensions.NotRequired[typing_extensions.Annotated[int, FieldMetadata(alias="pageNumber")]]
    """
    The page number the bounding box appears on, using a 1-based array indexing (starts with page 1, not page 0)
    """

    top_left_x: typing_extensions.NotRequired[typing_extensions.Annotated[float, FieldMetadata(alias="topLeftX")]]
    """
    The x coordinate of the upper left corner of the bounding box
    """

    top_left_y: typing_extensions.NotRequired[typing_extensions.Annotated[float, FieldMetadata(alias="topLeftY")]]
    """
    The y coordinate of the upper left corner of the bounding box
    """
