# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
from .subscription_detail import SubscriptionDetailParams


class CustomerDetailParams(typing_extensions.TypedDict):
    """
    Account information for the user
    """

    email: typing_extensions.NotRequired[str]
    """
    Email associated with the account
    """

    first: typing_extensions.NotRequired[str]
    """
    Given name associated with the account, if known
    """

    last: typing_extensions.NotRequired[str]
    """
    Family name associated with the account, if known
    """

    subscription: typing_extensions.NotRequired[SubscriptionDetailParams]
