# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .customer_detail import CustomerDetailParams


class CustomerResponseParams(typing_extensions.TypedDict):
    customer: CustomerDetailParams
