# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
from .document_detail import DocumentDetailParams


class DocumentResponseParams(typing_extensions.TypedDict):
    document: typing_extensions.NotRequired[DocumentDetailParams]
