# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
import typing
from .document_detail import DocumentDetailParams
from ..core.serialization import FieldMetadata


class DocumentLookupResponseParams(typing_extensions.TypedDict):
    count: typing_extensions.NotRequired[int]
    """
    The number of results returned in the current response
    """

    documents: typing_extensions.NotRequired[typing.Sequence[DocumentDetailParams]]
    next_token: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="nextToken")]]
    total: typing_extensions.NotRequired[int]
    """
    The total number of results found
    """
