# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
from ..core.serialization import FieldMetadata
from ..types.document_type import DocumentType
import typing
from ..types.processing_status import ProcessingStatus


class DocumentDetailParams(typing_extensions.TypedDict):
    bucket_id: typing_extensions.NotRequired[typing_extensions.Annotated[int, FieldMetadata(alias="bucketId")]]
    document_id: typing_extensions.Annotated[str, FieldMetadata(alias="documentId")]
    """
    Unique system generated ID for the document
    """

    file_name: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="fileName")]]
    file_size: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="fileSize")]]
    """
    The file size of the file stored in GroundX
    """

    file_type: typing_extensions.NotRequired[typing_extensions.Annotated[DocumentType, FieldMetadata(alias="fileType")]]
    process_id: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="processId")]]
    """
    Unique system generated ID for the ingest request
    """

    search_data: typing_extensions.NotRequired[
        typing_extensions.Annotated[typing.Dict[str, typing.Optional[typing.Any]], FieldMetadata(alias="searchData")]
    ]
    source_url: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="sourceUrl")]]
    """
    Source document URL
    """

    status: typing_extensions.NotRequired[ProcessingStatus]
    status_message: typing_extensions.NotRequired[
        typing_extensions.Annotated[str, FieldMetadata(alias="statusMessage")]
    ]
    xray_url: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="xrayUrl")]]
    """
    Document X-Ray results
    """
