# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
import typing
from .group_detail import GroupDetailParams


class GroupListResponseParams(typing_extensions.TypedDict):
    groups: typing_extensions.NotRequired[typing.Sequence[GroupDetailParams]]
