# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .health_response_health import HealthResponseHealthParams


class HealthResponseParams(typing_extensions.TypedDict):
    health: HealthResponseHealthParams
