# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
import datetime as dt
from ..core.serialization import FieldMetadata
from ..types.health_service_status import HealthServiceStatus


class HealthServiceParams(typing_extensions.TypedDict):
    last_update: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="lastUpdate")]
    """
    The data time when the service status was last updated, in RFC3339 format
    """

    service: str
    """
    The name of the service
    """

    status: HealthServiceStatus
    """
    The health status of the service
    """
