# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
from ..core.serialization import FieldMetadata


class MeterDetailParams(typing_extensions.TypedDict):
    """
    Current usage and limits for the user for the given metric
    """

    max: typing_extensions.NotRequired[int]
    """
    Maximum limit for the current billing period
    """

    meter_id: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="meterId")]]
    """
    Unique system generated ID for the meteric
    """

    value: typing_extensions.NotRequired[int]
    """
    Current usage for the current billing period
    """
