# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
from ..core.serialization import FieldMetadata
from .process_status_response_ingest_progress import ProcessStatusResponseIngestProgressParams
from ..types.processing_status import ProcessingStatus


class ProcessStatusResponseIngestParams(typing_extensions.TypedDict):
    process_id: typing_extensions.Annotated[str, FieldMetadata(alias="processId")]
    progress: typing_extensions.NotRequired[ProcessStatusResponseIngestProgressParams]
    status: ProcessingStatus
    status_message: typing_extensions.NotRequired[
        typing_extensions.Annotated[str, FieldMetadata(alias="statusMessage")]
    ]
