# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .process_status_response_ingest import ProcessStatusResponseIngestParams


class ProcessStatusResponseParams(typing_extensions.TypedDict):
    ingest: ProcessStatusResponseIngestParams
