# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .api_key_detail import ApiKeyDetail


class ApiKeyResponse(UniversalBaseModel):
    api_keys: typing_extensions.Annotated[
        typing.Optional[typing.List[ApiKeyDetail]], FieldMetadata(alias="apiKeys"), pydantic.Field(alias="apiKeys")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
