# This file was auto-generated by Fern from our API Definition.

import typing

CustomWorkflowOutputRouteOutputMap = typing.Union[
    typing.Literal["customChunkOutputs", "customSectionOutputs", "customDocumentOutputs"], typing.Any
]
