# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .custom_workflow_output_route_level import CustomWorkflowOutputRouteLevel
from .custom_workflow_output_route_output_map import CustomWorkflowOutputRouteOutputMap


class CustomWorkflowOutputRoute(UniversalBaseModel):
    """
    Public custom output route metadata. Each route must have exactly one matching leafFields record on finalPath, workflowGroup, workflowField, stepName, level, and outputKey.
    """

    workflow_group: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="workflowGroup"),
        pydantic.Field(alias="workflowGroup", description="Workflow extraction group that owns the routed field."),
    ]
    workflow_field: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="workflowField"),
        pydantic.Field(alias="workflowField", description="Workflow extraction field routed to the final JSON path."),
    ]
    final_path: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="finalPath"),
        pydantic.Field(
            alias="finalPath",
            description="RFC 6901 JSON Pointer to the final JSON field. Repeated item paths use a literal * segment as a schema wildcard; for example, the pointer with segments fees, *, and amount represents a repeated item amount.",
        ),
    ]
    step_name: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="stepName"),
        pydantic.Field(alias="stepName", description="Canonical custom step name that produced the output."),
    ]
    level: CustomWorkflowOutputRouteLevel
    output_map: typing_extensions.Annotated[
        CustomWorkflowOutputRouteOutputMap,
        FieldMetadata(alias="outputMap"),
        pydantic.Field(
            alias="outputMap",
            description="Custom X-Ray output map that stores this route's values. The map must match level.",
        ),
    ]
    output_key: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="outputKey"),
        pydantic.Field(alias="outputKey", description="Lower-snake output key for this custom step output."),
    ]
    readback_path: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="readbackPath"),
        pydantic.Field(
            alias="readbackPath", description="Canonical non-page X-Ray/readback path template for this routed output."
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
