# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .custom_workflow_leaf_field_level import CustomWorkflowLeafFieldLevel
from .custom_workflow_leaf_field_repetition_scope import CustomWorkflowLeafFieldRepetitionScope


class CustomWorkflowLeafField(UniversalBaseModel):
    """
    Public custom leaf-field metadata used for route integrity and executable-step field-count validation.
    """

    final_path: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="finalPath"),
        pydantic.Field(
            alias="finalPath",
            description="RFC 6901 JSON Pointer to the prompted final schema leaf. Repeated item paths use a literal * segment and count once per prompted schema leaf.",
        ),
    ]
    workflow_group: typing_extensions.Annotated[
        str, FieldMetadata(alias="workflowGroup"), pydantic.Field(alias="workflowGroup")
    ]
    workflow_field: typing_extensions.Annotated[
        str, FieldMetadata(alias="workflowField"), pydantic.Field(alias="workflowField")
    ]
    step_name: typing_extensions.Annotated[str, FieldMetadata(alias="stepName"), pydantic.Field(alias="stepName")]
    level: CustomWorkflowLeafFieldLevel
    output_key: typing_extensions.Annotated[str, FieldMetadata(alias="outputKey"), pydantic.Field(alias="outputKey")]
    field_type: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="fieldType"),
        pydantic.Field(alias="fieldType", description="Final schema field type for this prompted leaf."),
    ]
    is_repeated: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="isRepeated"),
        pydantic.Field(
            alias="isRepeated", description="Whether this leaf belongs to a repeated/list field definition."
        ),
    ]
    repetition_scope: typing_extensions.Annotated[
        CustomWorkflowLeafFieldRepetitionScope,
        FieldMetadata(alias="repetitionScope"),
        pydantic.Field(
            alias="repetitionScope",
            description="none is valid only for non-repeated leaves; field counts a repeated value as one prompted leaf; item uses literal * path segments for prompted item leaves.",
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
