# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .workflow_engine import WorkflowEngine
from .workflow_prompt_group import WorkflowPromptGroup


class CustomWorkflowStepElementConfig(UniversalBaseModel):
    """
    Element-level custom workflow step config. It supports existing prompt, engine, and include settings; fixed-output field is omitted because custom output routing is defined by outputRoutes and leafFields.
    """

    engine: typing.Optional[WorkflowEngine] = None
    includes: typing.Optional[typing.Dict[str, bool]] = None
    prompt: typing.Optional[WorkflowPromptGroup] = pydantic.Field(default=None)
    """
    Prompt group for this custom step element config. On workflow update, omit prompt or send an empty object to use the default prompt group, send an object to customize supplied prompt members, and send null to use no prompt group.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
