# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .custom_workflow_step_config import CustomWorkflowStepConfig
from .custom_workflow_step_kind import CustomWorkflowStepKind
from .custom_workflow_step_level import CustomWorkflowStepLevel


class CustomWorkflowStep(UniversalBaseModel):
    """
    Workflow-level custom extraction step definition. Fixed workflow steps remain under steps.
    """

    name: str = pydantic.Field()
    """
    Canonical lower-snake custom step name. Names are globally unique and cannot collide with fixed step names or reserved workflow metadata names.
    """

    level: CustomWorkflowStepLevel = pydantic.Field()
    """
    Output level for the custom step.
    """

    kind: CustomWorkflowStepKind = pydantic.Field()
    """
    Output kind for the custom step. Valid combinations are chunk/section with instruct, keys, or summary; document with keys or summary.
    """

    config: typing.Optional[CustomWorkflowStepConfig] = None
    required_template_keys: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="requiredTemplateKeys"),
        pydantic.Field(
            alias="requiredTemplateKeys",
            description="Workflow template keys required by this custom step. Keys follow the same normalization and validation rules as template keys.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
