# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .customer_usage_detail_metric import CustomerUsageDetailMetric


class CustomerUsageDetail(UniversalBaseModel):
    """
    Aggregate customer usage for a requested time period.
    """

    metric: CustomerUsageDetailMetric = pydantic.Field()
    """
    Supported usage metric queried.
    """

    meter_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="meterId"),
        pydantic.Field(
            alias="meterId",
            description="Unique system generated ID for the usage meter resolved from the authenticated account.",
        ),
    ] = None
    value: int = pydantic.Field()
    """
    Aggregate usage value for the requested time period.
    """

    start_time: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="startTime"),
        pydantic.Field(alias="startTime", description="Inclusive UTC window start used for the usage query."),
    ]
    end_time: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="endTime"),
        pydantic.Field(alias="endTime", description="Exclusive UTC window end used for the usage query."),
    ]
    usage_as_of: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="usageAsOf"),
        pydantic.Field(alias="usageAsOf", description="Time when GroundX read the latest available usage summary."),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
