# This file was auto-generated by Fern from our API Definition.

import typing

CustomerDetailStatus = typing.Union[
    typing.Literal[
        "admin", "apiKey", "archived", "invalid", "partnerApiKey", "partnerModUser", "partner", "test", "user"
    ],
    typing.Any,
]
