# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .custom_workflow_step_element_config import CustomWorkflowStepElementConfig


class CustomWorkflowStepConfig(UniversalBaseModel):
    """
    Custom workflow step config keyed by element type. Element configs omit fixed-output field; custom output storage is derived from level, kind, outputRoutes, and leafFields.
    """

    all_: typing_extensions.Annotated[
        typing.Optional[CustomWorkflowStepElementConfig], FieldMetadata(alias="all"), pydantic.Field(alias="all")
    ] = None
    figure: typing.Optional[CustomWorkflowStepElementConfig] = None
    json_: typing_extensions.Annotated[
        typing.Optional[CustomWorkflowStepElementConfig], FieldMetadata(alias="json"), pydantic.Field(alias="json")
    ] = None
    paragraph: typing.Optional[CustomWorkflowStepElementConfig] = None
    table: typing.Optional[CustomWorkflowStepElementConfig] = None
    table_figure: typing_extensions.Annotated[
        typing.Optional[CustomWorkflowStepElementConfig],
        FieldMetadata(alias="table-figure"),
        pydantic.Field(alias="table-figure"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
