# This file was auto-generated by Fern from our API Definition.

import typing

CustomWorkflowOutputMap = typing.Dict[str, typing.Dict[str, typing.Any]]
"""
Map from custom workflow step name to output key/value pairs.
"""
