# This file was auto-generated by Fern from our API Definition.

import typing

DocumentDetailDeliveryStatus = typing.Union[
    typing.Literal["not_configured", "pending", "succeeded", "failed", "unknown"], typing.Any
]
