# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class DocumentUpdate(UniversalBaseModel):
    document_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="documentId"),
        pydantic.Field(alias="documentId", description="The document ID of the file you wish to update."),
    ]
    file_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="fileName"),
        pydantic.Field(alias="fileName", description="The name you wish to change for the file."),
    ] = None
    filter: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    A dictionary of key-value pairs that will replace the existing filter.
    """

    search_data: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]],
        FieldMetadata(alias="searchData"),
        pydantic.Field(
            alias="searchData", description="A dictionary of key-value pairs that will replace the existing searchData."
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
