# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .document_xray_chunk import DocumentXrayChunk


class DocumentXrayPage(UniversalBaseModel):
    """
    X-Ray page data, including page-local chunks when returned by the runtime.
    """

    chunks: typing.Optional[typing.List[DocumentXrayChunk]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
