# This file was auto-generated by Fern from our API Definition.

import typing

from .document_update_request_item import DocumentUpdateRequestItem

DocumentUpdateRequest = typing.List[DocumentUpdateRequestItem]
