# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .custom_workflow_output_map import CustomWorkflowOutputMap


class DocumentXrayChunk(UniversalBaseModel):
    """
    X-Ray chunk data. Known custom output maps are typed while legacy and system-generated fields remain additive.
    """

    custom_chunk_outputs: typing_extensions.Annotated[
        typing.Optional[CustomWorkflowOutputMap],
        FieldMetadata(alias="customChunkOutputs"),
        pydantic.Field(alias="customChunkOutputs"),
    ] = None
    custom_section_outputs: typing_extensions.Annotated[
        typing.Optional[CustomWorkflowOutputMap],
        FieldMetadata(alias="customSectionOutputs"),
        pydantic.Field(alias="customSectionOutputs"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
