# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .custom_workflow_output_map import CustomWorkflowOutputMap
from .document_xray_chunk import DocumentXrayChunk
from .document_xray_page import DocumentXrayPage


class DocumentXray(UniversalBaseModel):
    """
    Document X-Ray data. Custom outputs are exposed through level-specific maps and fixed legacy fields remain additive.
    """

    chunks: typing.Optional[typing.List[DocumentXrayChunk]] = None
    custom_document_outputs: typing_extensions.Annotated[
        typing.Optional[CustomWorkflowOutputMap],
        FieldMetadata(alias="customDocumentOutputs"),
        pydantic.Field(alias="customDocumentOutputs"),
    ] = None
    document_pages: typing_extensions.Annotated[
        typing.Optional[typing.List[DocumentXrayPage]],
        FieldMetadata(alias="documentPages"),
        pydantic.Field(alias="documentPages"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
