# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ExtractionProvenance(UniversalBaseModel):
    """
    Workflow and runtime builds associated with the document's current extraction result.
    """

    artifact_revision: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="artifactRevision"),
        pydantic.Field(
            alias="artifactRevision",
            description="Revision of the complete deployed workflow artifact, including prompts.",
        ),
    ] = None
    runtime_build_ids: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="runtimeBuildIds"),
        pydantic.Field(
            alias="runtimeBuildIds",
            description="Unique extraction container build IDs observed while producing the current result. Each ID maps to one immutable image digest.",
        ),
    ] = None
    schema_hash: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="schemaHash"),
        pydantic.Field(alias="schemaHash", description="Hash of the workflow output schema and routing metadata."),
    ] = None
    workflow_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="workflowId"),
        pydantic.Field(alias="workflowId", description="Unique system generated ID for the extraction workflow."),
    ] = None
    workflow_version: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="workflowVersion"),
        pydantic.Field(
            alias="workflowVersion", description="Exact workflow version selected when extraction was dispatched."
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
