# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .health_service_status import HealthServiceStatus


class HealthService(UniversalBaseModel):
    last_update: dt.datetime = pydantic.Field(alias="lastUpdate")
    """
    The data time when the service status was last updated, in RFC3339 format
    """

    service: str = pydantic.Field()
    """
    The name of the service
    """

    status: HealthServiceStatus = pydantic.Field()
    """
    The health status of the service
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
