# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .ingest_status_progress import IngestStatusProgress
from .processing_status import ProcessingStatus


class IngestStatus(UniversalBaseModel):
    id: typing.Optional[int] = None
    process_id: str = pydantic.Field(alias="processId")
    progress: typing.Optional[IngestStatusProgress] = None
    status: ProcessingStatus
    status_message: typing.Optional[str] = pydantic.Field(alias="statusMessage", default=None)

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
