# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .subscription_detail_meters import SubscriptionDetailMeters


class SubscriptionDetail(UniversalBaseModel):
    """
    Subscription information for the user, including current usage and limits
    """

    billing_cycle_anchor: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="billingCycleAnchor"),
        pydantic.Field(alias="billingCycleAnchor", description="Billing cycle anchor for the current subscription."),
    ] = None
    billing_start: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="billingStart"),
        pydantic.Field(alias="billingStart", description="Start of the billing period used for current usage values."),
    ] = None
    billing_end: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="billingEnd"),
        pydantic.Field(
            alias="billingEnd", description="End of the billing period used for current usage values, when available."
        ),
    ] = None
    meters: typing.Optional[SubscriptionDetailMeters] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
