# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .meter_detail import MeterDetail


class SubscriptionDetailMeters(UniversalBaseModel):
    file_tokens: typing.Optional[MeterDetail] = pydantic.Field(alias="fileTokens", default=None)
    searches: typing.Optional[MeterDetail] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
