# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .workflow_prompt_role import WorkflowPromptRole


class WorkflowPrompt(UniversalBaseModel):
    """
    Configurations for the prompt an agent uses in a workflow
    """

    abbreviated: typing.Optional[str] = pydantic.Field(default=None)
    """
    A short version of the prompt that is included in historical chat transcripts as part of the prompt context
    """

    additional_context: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="additionalContext"),
        pydantic.Field(
            alias="additionalContext",
            description="Supplemental context appended to the default full request or task prompt. Server validation authoritatively limits this value to 4096 UTF-8 bytes. When omitted, rendered prompt output is unchanged. Workflow-level template.CUSTOM_INSTRUCTIONS remains a global fallback, and a prompt-member additionalContext takes precedence for that member. It is supported only on fixed workflow default request/task prompt members for GPT and EyeLevel workflows; because this shared schema also appears under custom workflow prompt shapes, server validation rejects additionalContext under customSteps, useExtras, or prompt members that replace the full prompt.",
        ),
    ] = None
    prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    The prompt that is sent to the LLM
    """

    role: typing.Optional[WorkflowPromptRole] = pydantic.Field(default=None)
    """
    An enumerated value that conforms to OpenAI '/chat/completion' specifications
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
