# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .workflow_engine_reasoning_effort import WorkflowEngineReasoningEffort
from .workflow_engine_service import WorkflowEngineService


class WorkflowEngine(UniversalBaseModel):
    """
    Configurations for the LLM an agent uses in a workflow
    """

    api_key: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="apiKey"),
        pydantic.Field(
            alias="apiKey", description="Credential sent using the selected service's authentication scheme"
        ),
    ] = None
    base_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="baseURL"),
        pydantic.Field(alias="baseURL", description="The provider base URL used for requests by the selected service"),
    ] = None
    engine_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="engineID"),
        pydantic.Field(alias="engineID", description="The model name that will be included in the request"),
    ] = None
    max_images: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="maxImages"),
        pydantic.Field(
            alias="maxImages",
            description="Maximum number of image attachments sent in one request using this workflow engine. GroundX removes earlier images when the request exceeds the limit, while preserving text and later images. Omit to use the default limit of 50. An explicit value takes precedence. Workflow and step engine settings follow normal engine precedence; no separate route-specific image-count value overrides the selected engine. The independent openai-base64 serialized request-size guard still applies.",
        ),
    ] = None
    reasoning_effort: typing_extensions.Annotated[
        typing.Optional[WorkflowEngineReasoningEffort],
        FieldMetadata(alias="reasoningEffort"),
        pydantic.Field(
            alias="reasoningEffort",
            description="An enumerated value that conforms to OpenAI '/chat/completion' specifications",
        ),
    ] = None
    request_headers: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, str]],
        FieldMetadata(alias="requestHeaders"),
        pydantic.Field(
            alias="requestHeaders",
            description="Headers added to the LLM request, for example 'OpenAI-Project' to attribute usage. Values must be strings. Your header wins if it collides with one GroundX sets. Requires apiKey on the same engine: without it the request uses GroundX's credential, so a workflow create or update that sets requestHeaders and omits apiKey is rejected. Headers are sent as-is; GroundX does not guarantee a provider acts on any given header.",
        ),
    ] = None
    request_passthrough: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]],
        FieldMetadata(alias="requestPassthrough"),
        pydantic.Field(
            alias="requestPassthrough",
            description="A JSON object merged into the LLM request body after GroundX builds the standard request. Values in this object override generated request fields on key conflicts.",
        ),
    ] = None
    service: typing.Optional[WorkflowEngineService] = pydantic.Field(default=None)
    """
    Selects how requests are configured for the provider. Anthropic uses the native Messages API with baseURL, apiKey, engineID, requestHeaders, and requestPassthrough.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
