# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .custom_workflow_leaf_field import CustomWorkflowLeafField
from .custom_workflow_output_route import CustomWorkflowOutputRoute
from .custom_workflow_step import CustomWorkflowStep
from .workflow_request_chunk_strategy import WorkflowRequestChunkStrategy
from .workflow_request_section_strategy import WorkflowRequestSectionStrategy
from .workflow_steps import WorkflowSteps
from .workflow_template import WorkflowTemplate


class WorkflowRequest(UniversalBaseModel):
    chunk_strategy: typing_extensions.Annotated[
        typing.Optional[WorkflowRequestChunkStrategy],
        FieldMetadata(alias="chunkStrategy"),
        pydantic.Field(alias="chunkStrategy"),
    ] = None
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the workflow being created.
    """

    yaml: typing.Optional[str] = pydantic.Field(default=None)
    """
    Workflow YAML. GroundX validates it and creates the workflow settings. When yaml is supplied, omit extract, customSteps, outputRoutes, leafFields, and steps. A v1 workflow declares extraction_policy_version, workflow.custom_steps, workflow.agent_chain, a workflow_step and role for each group, and a workflow_output_key for each routed field. repeats: true declares an array of records; unique_attrs names fields used to identify the same record. For related lists, match_attrs names the shared fields and passthrough.from names the parent group. String matching ignores capitalization and surrounding whitespace. Blank or missing values do not match. When several parents match, GroundX uses the first. Group names and workflow_output_key values become output names.
    """

    extract: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Extract agent definitions.
    """

    template: typing.Optional[WorkflowTemplate] = None
    section_strategy: typing_extensions.Annotated[
        typing.Optional[WorkflowRequestSectionStrategy],
        FieldMetadata(alias="sectionStrategy"),
        pydantic.Field(alias="sectionStrategy"),
    ] = None
    steps: typing.Optional[WorkflowSteps] = None
    custom_steps: typing_extensions.Annotated[
        typing.Optional[typing.List[CustomWorkflowStep]],
        FieldMetadata(alias="customSteps"),
        pydantic.Field(
            alias="customSteps",
            description="Workflow-level custom extraction steps. Legacy fixed steps remain under steps.",
        ),
    ] = None
    output_routes: typing_extensions.Annotated[
        typing.Optional[typing.List[CustomWorkflowOutputRoute]],
        FieldMetadata(alias="outputRoutes"),
        pydantic.Field(
            alias="outputRoutes",
            description="Custom output routes. Each record must have exactly one matching leafFields record on finalPath, workflowGroup, workflowField, stepName, level, and outputKey.",
        ),
    ] = None
    leaf_fields: typing_extensions.Annotated[
        typing.Optional[typing.List[CustomWorkflowLeafField]],
        FieldMetadata(alias="leafFields"),
        pydantic.Field(
            alias="leafFields",
            description="Custom leaf-field metadata used to validate route integrity and executable-step field counts.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
