# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .custom_workflow_leaf_field import CustomWorkflowLeafField
from .custom_workflow_output_route import CustomWorkflowOutputRoute
from .custom_workflow_step import CustomWorkflowStep
from .workflow_detail_chunk_strategy import WorkflowDetailChunkStrategy
from .workflow_detail_relationships import WorkflowDetailRelationships
from .workflow_detail_section_strategy import WorkflowDetailSectionStrategy
from .workflow_steps import WorkflowSteps
from .workflow_template import WorkflowTemplate


class WorkflowDetail(UniversalBaseModel):
    """
    Workflow information
    """

    chunk_strategy: typing_extensions.Annotated[
        typing.Optional[WorkflowDetailChunkStrategy],
        FieldMetadata(alias="chunkStrategy"),
        pydantic.Field(alias="chunkStrategy"),
    ] = None
    document_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="documentId"),
        pydantic.Field(alias="documentId", description="The documentId associated with the workflow"),
    ] = None
    id: typing.Optional[int] = pydantic.Field(default=None)
    """
    The bucketId or groupId associated with the workflow
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The human-readable name of the workflow
    """

    extract: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Extract agent definitions.
    """

    template: typing.Optional[WorkflowTemplate] = None
    section_strategy: typing_extensions.Annotated[
        typing.Optional[WorkflowDetailSectionStrategy],
        FieldMetadata(alias="sectionStrategy"),
        pydantic.Field(alias="sectionStrategy"),
    ] = None
    steps: typing.Optional[WorkflowSteps] = None
    custom_steps: typing_extensions.Annotated[
        typing.Optional[typing.List[CustomWorkflowStep]],
        FieldMetadata(alias="customSteps"),
        pydantic.Field(
            alias="customSteps",
            description="Workflow-level custom extraction steps. Legacy fixed steps remain under steps.",
        ),
    ] = None
    output_routes: typing_extensions.Annotated[
        typing.Optional[typing.List[CustomWorkflowOutputRoute]],
        FieldMetadata(alias="outputRoutes"),
        pydantic.Field(
            alias="outputRoutes",
            description="Custom output routes. Each record must have exactly one matching leafFields record on finalPath, workflowGroup, workflowField, stepName, level, and outputKey.",
        ),
    ] = None
    leaf_fields: typing_extensions.Annotated[
        typing.Optional[typing.List[CustomWorkflowLeafField]],
        FieldMetadata(alias="leafFields"),
        pydantic.Field(
            alias="leafFields",
            description="Custom leaf-field metadata used to validate route integrity and executable-step field counts.",
        ),
    ] = None
    relationships: typing.Optional[WorkflowDetailRelationships] = pydantic.Field(default=None)
    """
    Information describing what the workflow is associated with
    """

    workflow_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="workflowId"),
        pydantic.Field(alias="workflowId", description="Unique system generated ID for the workflow"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
