# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .workflow_step import WorkflowStep


class WorkflowStepsChunkInstruct(UniversalBaseModel):
    figure: typing.Optional[WorkflowStep] = None
    json_: typing_extensions.Annotated[typing.Optional[WorkflowStep], FieldMetadata(alias="json")] = None
    table_figure: typing_extensions.Annotated[typing.Optional[WorkflowStep], FieldMetadata(alias="table-figure")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
