# This file was auto-generated by Fern from our API Definition.

import typing

WorkflowTemplate = typing.Dict[str, str]
"""
Workflow-level prompt template values used by fixed and custom workflow step prompts.
"""
