# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .workflow_steps_chunk_instruct import WorkflowStepsChunkInstruct
from .workflow_steps_chunk_summary import WorkflowStepsChunkSummary
from .workflow_steps_doc_keys import WorkflowStepsDocKeys
from .workflow_steps_doc_summary import WorkflowStepsDocSummary
from .workflow_steps_search_query import WorkflowStepsSearchQuery
from .workflow_steps_sect_instruct import WorkflowStepsSectInstruct
from .workflow_steps_sect_summary import WorkflowStepsSectSummary


class WorkflowSteps(UniversalBaseModel):
    """
    A collection of workflow steps
    """

    chunk_instruct: typing_extensions.Annotated[
        typing.Optional[WorkflowStepsChunkInstruct], FieldMetadata(alias="chunk-instruct")
    ] = None
    chunk_summary: typing_extensions.Annotated[
        typing.Optional[WorkflowStepsChunkSummary], FieldMetadata(alias="chunk-summary")
    ] = None
    doc_keys: typing_extensions.Annotated[typing.Optional[WorkflowStepsDocKeys], FieldMetadata(alias="doc-keys")] = None
    doc_summary: typing_extensions.Annotated[
        typing.Optional[WorkflowStepsDocSummary], FieldMetadata(alias="doc-summary")
    ] = None
    search_query: typing_extensions.Annotated[
        typing.Optional[WorkflowStepsSearchQuery], FieldMetadata(alias="search-query")
    ] = None
    sect_instruct: typing_extensions.Annotated[
        typing.Optional[WorkflowStepsSectInstruct], FieldMetadata(alias="sect-instruct")
    ] = None
    sect_summary: typing_extensions.Annotated[
        typing.Optional[WorkflowStepsSectSummary], FieldMetadata(alias="sect-summary")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
