# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.customer_response import CustomerResponse
from ..types.customer_usage_response import CustomerUsageResponse
from .raw_client import AsyncRawCustomerClient, RawCustomerClient
from .types.customer_get_usage_request_metric import CustomerGetUsageRequestMetric


class CustomerClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCustomerClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCustomerClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCustomerClient
        """
        return self._raw_client

    def get(self, *, request_options: typing.Optional[RequestOptions] = None) -> CustomerResponse:
        """
        Get the account information associated with the API key.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CustomerResponse
            Look up success

        Examples
        --------
        from groundx import GroundX

        client = GroundX(
            api_key="YOUR_API_KEY",
        )
        client.customer.get()
        """
        _response = self._raw_client.get(request_options=request_options)
        return _response.data

    def get_usage(
        self,
        *,
        metric: CustomerGetUsageRequestMetric,
        start_time: dt.datetime,
        end_time: dt.datetime,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CustomerUsageResponse:
        """
        Get aggregate usage for the authenticated customer over a requested time period.

        The API resolves the account subscription and usage meter from the authenticated account. Do not provide customer ids, subscription ids, or meter ids. `startTime` is inclusive, `endTime` is exclusive, and both timestamps must be RFC3339 values aligned to minute boundaries. Timestamps are normalized to UTC. `endTime` cannot be in the future, windows longer than 366 days are rejected, and `usageAsOf` reflects the latest usage summary available to GroundX.

        Parameters
        ----------
        metric : CustomerGetUsageRequestMetric
            Supported usage metric to query.

        start_time : dt.datetime
            Inclusive RFC3339 window start. Must be aligned to a minute boundary.

        end_time : dt.datetime
            Exclusive RFC3339 window end. Must be aligned to a minute boundary and cannot be in the future.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CustomerUsageResponse
            Usage query success

        Examples
        --------
        import datetime

        from groundx import GroundX

        client = GroundX(
            api_key="YOUR_API_KEY",
        )
        client.customer.get_usage(
            metric="searches",
            start_time=datetime.datetime.fromisoformat(
                "2026-07-15 00:00:00+00:00",
            ),
            end_time=datetime.datetime.fromisoformat(
                "2026-07-29 00:00:00+00:00",
            ),
        )
        """
        _response = self._raw_client.get_usage(
            metric=metric, start_time=start_time, end_time=end_time, request_options=request_options
        )
        return _response.data


class AsyncCustomerClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCustomerClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCustomerClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCustomerClient
        """
        return self._raw_client

    async def get(self, *, request_options: typing.Optional[RequestOptions] = None) -> CustomerResponse:
        """
        Get the account information associated with the API key.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CustomerResponse
            Look up success

        Examples
        --------
        import asyncio

        from groundx import AsyncGroundX

        client = AsyncGroundX(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.customer.get()


        asyncio.run(main())
        """
        _response = await self._raw_client.get(request_options=request_options)
        return _response.data

    async def get_usage(
        self,
        *,
        metric: CustomerGetUsageRequestMetric,
        start_time: dt.datetime,
        end_time: dt.datetime,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CustomerUsageResponse:
        """
        Get aggregate usage for the authenticated customer over a requested time period.

        The API resolves the account subscription and usage meter from the authenticated account. Do not provide customer ids, subscription ids, or meter ids. `startTime` is inclusive, `endTime` is exclusive, and both timestamps must be RFC3339 values aligned to minute boundaries. Timestamps are normalized to UTC. `endTime` cannot be in the future, windows longer than 366 days are rejected, and `usageAsOf` reflects the latest usage summary available to GroundX.

        Parameters
        ----------
        metric : CustomerGetUsageRequestMetric
            Supported usage metric to query.

        start_time : dt.datetime
            Inclusive RFC3339 window start. Must be aligned to a minute boundary.

        end_time : dt.datetime
            Exclusive RFC3339 window end. Must be aligned to a minute boundary and cannot be in the future.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CustomerUsageResponse
            Usage query success

        Examples
        --------
        import asyncio
        import datetime

        from groundx import AsyncGroundX

        client = AsyncGroundX(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.customer.get_usage(
                metric="searches",
                start_time=datetime.datetime.fromisoformat(
                    "2026-07-15 00:00:00+00:00",
                ),
                end_time=datetime.datetime.fromisoformat(
                    "2026-07-29 00:00:00+00:00",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_usage(
            metric=metric, start_time=start_time, end_time=end_time, request_options=request_options
        )
        return _response.data
